# Generated by Django 3.2.4 on 2021-06-22 13:12

from django.db import migrations, models
import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(null=True, upload_to=status.models.upload_status_image),
        ),
    ]
